"""The bashi module."""

from bashi.types import (
    Parameter,
    ValueName,
    ValueVersion,
    ParameterValue,
    ParameterValueList,
    ParameterValueMatrix,
    ParameterValuePair,
    ParameterValueTuple,
    Combination,
    CombinationList,
    ParsableValueVersion,
    RegularParsableParameterSingle,
    CompilerParsableParameterSingle,
    ParsableParameterSingle,
    CompilerBackendCombination,
)
from bashi.globals import (
    HOST_COMPILER,
    DEVICE_COMPILER,
    GCC,
    CLANG,
    NVCC,
    CLANG_CUDA,
    HIPCC,
    ICPX,
    COMPILERS,
    ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLE,
    ALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLE,
    ALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLE,
    ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLE,
    ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLE,
    ALPAKA_ACC_GPU_CUDA_ENABLE,
    ALPAKA_ACC_GPU_HIP_ENABLE,
    ALPAKA_ACC_ONEAPI_CPU_ENABLE,
    ALPAKA_ACC_ONEAPI_GPU_ENABLE,
    ALPAKA_ACC_ONEAPI_FPGA_ENABLE,
    CPU_BACKENDS,
    ONE_API_BACKENDS,
    BACKENDS,
    UBUNTU,
    CMAKE,
    BOOST,
    CXX_STANDARD,
    OFF,
    ON,
    OFF_VER,
    ON_VER,
    ANY_PARAM,
    ANY_NAME,
    ANY_VERSION,
    PARAMETERS,
    RT_AVAILABLE_HIP_SDK_UBUNTU_VER,
    RT_AVAILABLE_CUDA_SDK_UBUNTU_VER,
    FilterDebugMode,
)
from bashi.version.utils import get_parameter_value_matrix
from bashi.version.relation import VersionRelation
from bashi.generator import get_runtime_infos, generate_combination_list
from bashi.utils import (
    check_parameter_value_pair_in_combination_list,
    check_unexpected_parameter_value_pair_in_combination_list,
    remove_parameter_value_pairs,
    remove_parameter_value_pairs_ranges,
    parse_value_version,
    parse_parameter_single,
    parse_combination,
)
from bashi.printer import (
    get_str_row_nice,
    print_row_nice,
    add_print_row_nice_parameter_alias,
    add_print_row_nice_version_alias,
    ubuntu_version_to_string,
    on_off_ver_to_str,
)
from bashi.filter_base import FilterBase
from bashi.results import get_expected_bashi_parameter_value_pairs
from bashi.row import BashiRow
from bashi.filter_utils import all_backends_fine, get_valid_compiler_backend_combinations
from bashi.result_modules.custom_verifier import remove_unsupported_compiler_backend_combinations

__all__ = [
    "Parameter",
    "ValueName",
    "ValueVersion",
    "ParameterValue",
    "ParameterValueList",
    "ParameterValueMatrix",
    "ParameterValuePair",
    "ParameterValueTuple",
    "Combination",
    "CombinationList",
    "ParsableValueVersion",
    "RegularParsableParameterSingle",
    "CompilerParsableParameterSingle",
    "ParsableParameterSingle",
    "CompilerBackendCombination",
    "HOST_COMPILER",
    "DEVICE_COMPILER",
    "GCC",
    "CLANG",
    "NVCC",
    "CLANG_CUDA",
    "HIPCC",
    "ICPX",
    "COMPILERS",
    "ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLE",
    "ALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLE",
    "ALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLE",
    "ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLE",
    "ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLE",
    "ALPAKA_ACC_GPU_CUDA_ENABLE",
    "ALPAKA_ACC_GPU_HIP_ENABLE",
    "ALPAKA_ACC_ONEAPI_CPU_ENABLE",
    "ALPAKA_ACC_ONEAPI_GPU_ENABLE",
    "ALPAKA_ACC_ONEAPI_FPGA_ENABLE",
    "CPU_BACKENDS",
    "ONE_API_BACKENDS",
    "BACKENDS",
    "UBUNTU",
    "CMAKE",
    "BOOST",
    "CXX_STANDARD",
    "OFF",
    "ON",
    "OFF_VER",
    "ON_VER",
    "ANY_PARAM",
    "ANY_NAME",
    "ANY_VERSION",
    "PARAMETERS",
    "RT_AVAILABLE_HIP_SDK_UBUNTU_VER",
    "RT_AVAILABLE_CUDA_SDK_UBUNTU_VER",
    "get_parameter_value_matrix",
    "VersionRelation",
    "get_runtime_infos",
    "generate_combination_list",
    "check_parameter_value_pair_in_combination_list",
    "check_unexpected_parameter_value_pair_in_combination_list",
    "remove_parameter_value_pairs",
    "remove_parameter_value_pairs_ranges",
    "parse_value_version",
    "parse_parameter_single",
    "parse_combination",
    "get_str_row_nice",
    "print_row_nice",
    "add_print_row_nice_parameter_alias",
    "add_print_row_nice_version_alias",
    "ubuntu_version_to_string",
    "on_off_ver_to_str",
    "FilterBase",
    "get_expected_bashi_parameter_value_pairs",
    "BashiRow",
    "FilterDebugMode",
    "all_backends_fine",
    "get_valid_compiler_backend_combinations",
    "remove_unsupported_compiler_backend_combinations",
]
