name: test-and-deploy
on: [push, pull_request]
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11', '3.12', '3.13']
        name: Run unit tests with Python ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: ${{ matrix.python-version }}
                architecture: x64
            - name: Install bashi
              run: |
                pip install .
            - name: run unit tests
              run: python -m unittest discover -s tests -p "*.py"
    integration-tests:
      needs: unit-tests
      runs-on: ubuntu-latest
      name: Run example/example.py as integration test
      steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: 3.13
                architecture: x64
            - name: Install bashi
              run: |
                pip install .
            - name: run integration test
              run: python example/example.py
            - name: copy example output for reproducible test
              run: mv example/job.yaml example/first.yaml
            - name: run example second time
              run: python example/example.py
            - name: compare result of example runs (should be equal)
              run: diff example/job.yaml example/first.yaml
